#!/bin/sh
# eric.mourgaya@arkea.com
# Apache Licence
### BEGIN INIT INFO
# Default-Start:     3 5 
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

RETVAL=0
PYTHONBIN=`which python`
function rbd_map(){
	rbd info cache/vbox &> /dev/null
	if [ ! $? -eq 0 ];then
		rbd create --size 2048G cache/vbox --image-feature layering &> /dev/null
		rbd map cache/vbox &> /dev/null
		mkfs.xfs -q /dev/rbd0 &> /dev/null
		mount -t xfs -o "rw,noexec,nodev,noatime,nodiratime,nobarrier,inode64,logbufs=8,logbsize=256k,allocsize=4M" /dev/rbd0 /home/vbox  &>/dev/null
	else
	    df | grep rbd0 &> /dev/null
		if [ ! $? -eq 0 ];then
			ls /dev/rbd0 &> /dev/null
			if [ $? -eq 0 ];then
				mount -t xfs -o "rw,noexec,nodev,noatime,nodiratime,nobarrier,inode64,logbufs=8,logbsize=256k,allocsize=4M" /dev/rbd0 /home/vbox &>/dev/null
			       echo aaa
			else
			      echo bbbb
				rbd map cache/vbox &> /dev/null
				mount -t xfs -o "rw,noexec,nodev,noatime,nodiratime,nobarrier,inode64,logbufs=8,logbsize=256k,allocsize=4M" /dev/rbd0 /home/vbox &> /dev/null
			fi
		fi
	fi
}

case "$1" in
  start)
    echo "Starting receive daemon"
    systemctl restart rabbitmq-server
    #rbd_map
    $PYTHONBIN /etc/init.d/receive.py start
    RETVAL=$?
    ;;
  stop)
    echo "Stopping  receive daemon" 
    $PYTHONBIN /etc/init.d/receive.py stop
    ;;
  restart)
    echo "Restarting  receive daemon" 
    $PYTHONBIN /etc/init.d/receive.py restart
    ;;
  status)
    echo "Status  receive daemon" 
    $PYTHONBIN /etc/init.d/receive.py status
    ;;
  *)
    echo "Usage: /etc/init.d/vboxagent {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0

