---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  yum: name={{ item }} state=present
  with_items:
   - mariadb-server
   - MySQL-python

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: Create Application DB User
  mysql_user: name=lc password='fuck' priv=*.*:ALL,GRANT state=present

- name: upload onethink data
  unarchive: src=onethink.tar.gz dest=/var/lib/mysql copy=yes owner=mysql mode=0755 group=mysql creates=/var/lib/mysql/onethink
  notify: restart mariadb
